CREATE DATABASE IF NOT EXISTS sistema CHARACTER SET utf8 COLLATE utf8_spanish_ci
USE USERS_DB;

CREATE TABLE IF NOT EXISTS USERS (
    user_id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(35) NOT NULL,
    password VARCHAR(40) NOT NULL,
    fist_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    PRIMARY KEY (people_id)
)ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_spanish_ci;